config/routes.rb
Pollster::Application.routes.draw do

  resources :polls do
    resources :questions do
    end
  end

  resources :questions do
    resources :answers 
    resources :responses
  end

  root to: 'polls#index'
  match "/:id" => redirect("/polls/%{id}/edit")

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :value
  belongs_to :question
  has_many :responses

  validates_presence_of :value
end

app/models/poll.rb
class Poll < ActiveRecord::Base
	extend FriendlyId
	attr_accessible :edit_slug, :name

	friendly_id :name, :use => :slugged

  before_create :generate_edit_slug

  validates_uniqueness_of :name, :case_sensitive => false

  has_many :questions


	private

	  def generate_edit_slug (salt = "dkjekdldc")
	  	self.edit_slug = Digest::MD5.hexdigest(self.id.to_s + self.name + salt)
	  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title
  belongs_to :poll
  has_many :responses
  has_many :answers

  validates_presence_of :title
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :answer_id, :question_id
  belongs_to :answer
  belongs_to :question

  validates_presence_of :answer, :question
  # validates_uniqueness_of :answer, :scope => :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def new
		@question = Question.find(params[:question_id])
  	@answer = @question.answers.new
	end

	def create
		@question = Question.find(params[:question_id])
  	@answer = @question.answers.new(params[:answer])
  	if @answer.save
  		redirect_to  edit_poll_question_path(@question.poll, @question), :flash => {:success => "Your answer has been saved successfully!"}
  	else
  		render 'new', :flash => {:error => "Something went wrong! Try Again."}
  	end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
	def index
		@polls = Poll.all
	end

	def new
		@poll = Poll.new
	end

	def create
		@poll = Poll.new(params[:poll])
		if @poll.save
			session[:stats] = @poll.name
			redirect_to edit_poll_path(@poll.edit_slug), :flash => {:success => "Poll sucessfully created! Your unique edit link is #{root_url}#{@poll.edit_slug}"}
		else
			render 'new', :notice => "Your Poll could not be completed."
		end
	end

	def show
		@poll = Poll.find(params[:id])
		@questions = @poll.questions
	end

	def edit
		@poll = Poll.find_by_edit_slug(params[:id])
		@questions =  @poll.questions
	end

	def update
		@poll = Poll.find(params[:id])
		if @poll.update_attributes(params[:poll])
			redirect_to :back, :flash => {:success => "Poll Updated."}
		else
			render :back, :flash => {:error => "Update unsuccessful. Please try again."}
		end
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
  	@poll = Poll.find(params[:poll_id])
  	@question = @poll.questions.new

  end

  def show
    @question = Question.find(params[:id])
    @next_question = @question.poll.questions.where("id > ?", params[:id]).first
    @response = Response.new
  end

  def create
  	@poll = Poll.find(params[:poll_id])
  	@question = @poll.questions.new(params[:question])
  	if @question.save
  		redirect_to edit_poll_path(@poll.edit_slug), :flash => {:success => "Your question has been saved successfully!"}
  	else
  		render 'new', :flash => {:error => "Something went wrong! Try Again."}
  	end
  end

  def edit
  	@poll = Poll.find(params[:poll_id])
  	@question = @poll.questions.find(params[:id])
  end

  def update
  	@question = Question.find(params[:id])
		if @question.update_attributes(params[:question])
			redirect_to edit_poll_path(@question.poll.edit_slug), :flash => {:success => "Question Updated."}
		else
			render :back, :flash => {:error => "Update unsuccessful. Please try again."}
		end
  end

  def destroy
    if Question.destroy(params[:id])
      redirect_to :back, :flash => {:success => "Question delete successfully."}
    else
      render :back, :flash => {:warning => "Question failed to delete"}
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def new
  	@response = Response.new
  end

  def create
    @question = Question.find(params[:question_id])
    warn "*******************************************"
    warn @question.poll.questions.where("id > ?", params[:question_id]).sort_by {|question| question.id }.first
    @next_question = @question.poll.questions.where("id > ?", params[:question_id]).sort_by {|question| question.id }.first
    @response = @question.responses.new
    answer = Answer.find(params[:answer_id])
    @response.answer = answer
  	#@response = Response.new(:question_id => params[:question_id], :answer_id => params[:answer_id])
    if @response.save
      if @next_question.nil?
        session[:stats] = @question.poll.name 
        redirect_to poll_path(@question.poll), :flash => {:success => "Survey Complete"}
      else
        redirect_to question_path(@next_question)
      end
    else
      redirect_to question_path(@question), :flash => {:error => "Update unsuccessful. Please try again."}
      # render 'questions/show', :flash => {:error => "Update unsuccessful. Please try again."}
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
	def generate_route_for_question
		if @next_question
			link_to "Next Question", question_path(@next_question)
		else
			link_to "Complete Poll", poll_path(@question.poll_id)
		end
	end

	def response_count(responable)
		responable.responses.count
	end

	def response_percentage(answer,question)
		((response_count(answer) /response_count(question).to_f)*100).round(2)
	end

	def poll_completed?
		session[:stats] == @poll.name	
	end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/answers/new.html.haml
=form_for([@question, @answer]) do |f|
	- if @answer.errors.any?
		%div.alert.alert-error
			%h2 #{ pluralize(@answer.errors.count, "error")} prevented this poll from being saved!
			%ul
				- @answer.errors.full_messages.each do |msg|
					%li #{msg}
	%p
		=f.label :value, "New Answer Value"
		=f.text_field :value
	%p
		=f.button "Add Answer", :class => "btn btn-success"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<% flash.each do |key, message| %>
  <%= content_tag :div, message, :class => "alert alert-#{key}" %>
<% end %>	

<%= yield %>

</body>
</html>

app/views/polls/_answer_responses.html.haml
-question.answers.each do |answer|
  %h4 #{answer.value}: #{response_percentage(answer,question)} %

app/views/polls/_form.html.haml
=form_for(@poll) do |f|
	- if @poll.errors.any?
		%div.alert.alert-error
			%h2 #{ pluralize(@poll.errors.count, "error")} prevented this poll from being saved!
			%ul
				- @poll.errors.full_messages.each do |msg|
					%li #{msg}
	%p
		=f.label :name
		=f.text_field :name
	%p
		=f.button btn_message, :class => "btn btn-success "

app/views/polls/_question_list.html.haml
%ol
	- @questions.each do |question|
		%li 
			%h3 #{question.title}
			-if poll_completed?
				%h4 
					%span.label.label-info #{response_count(question)} Responses
				=render 'answer_responses', :question => question

app/views/polls/edit.html.haml
%h1 Edit your Poll: #{@poll.name.upcase!}
%h3 
	Your Edit Link: 
	= link_to "#{root_url}#{@poll.edit_slug}", "#{root_path}#{@poll.edit_slug}"
=link_to "Add Question", new_poll_question_path(@poll), :class => "btn pull-right", :remote => true
%h3 
	Your Share Link: 
	=link_to "#{root_url}polls/#{@poll.slug}", "#{root_path}polls/#{@poll.slug}"


= render "form", :btn_message => "Edit Poll"

%ul.questions
	- @questions.each do |question|
		%li 
			%span #{question.title}
			%div.btn-group.pull-right
				=link_to "Edit", edit_poll_question_path(@poll , question), :class => "btn"
				=link_to "Delete", poll_question_path(@poll,question), :method => :delete, :class => "btn btn-danger delete"
 

app/views/polls/index.html.haml
=link_to "Create Your Own", new_poll_path, :class => "btn btn-large pull-right"

%h1 Find a poll!

%ul.polls
	- @polls.each do |poll|
		%li
			%h3
				=link_to poll.name, poll_path(poll)

app/views/polls/new.html.haml
%h1 Create a New Poll!
= render "form", :btn_message => "Create Poll"

app/views/polls/show.html.haml
%h1 #{@poll.name}

=link_to "Start the Quiz!", question_path(@questions.first), :class => "btn btn-success btn-large" unless poll_completed?

%h2 Questions
=render 'question_list'


			
					

app/views/questions/_form.html.haml
=form_for([@poll, @question]) do |f|
	- if @question.errors.any?
		%div.alert.alert-error
			%h2 #{ pluralize(@question.errors.count, "error")} prevented this poll from being saved!
			%ul
				- @question.errors.full_messages.each do |msg|
					%li #{msg}
	%p
		=f.label :title, "Question Prompt"
		=f.text_field :title
	%p
		=f.button btn_message, :class => "btn btn-success btn-primary"

app/views/questions/edit.html.haml
%h1 Edit: #{@question.title}
= render :partial => 'form', :locals => {:btn_message => "Update Question"}
%p
	=link_to "New Answer Choice", new_question_answer_path(@question), :class => "btn"
%ul.questions
	- @question.answers.each do |answer|
		%li #{answer.value}

= link_to "Back", edit_poll_path(@poll.edit_slug)

app/views/questions/new.html.haml
%h1 New Questions for #{@poll.name}
= render :partial => 'form', :locals => {:btn_message => "Create Question"}

app/views/questions/new.js.erb
$('body').append('<%= j(render '/shared/modal', :modal_title => "Create a new Question", :partial => 'questions/form', :partial_vars => {:btn_message => 'Create'}) %>');



$('#modal').modal('show');

app/views/questions/show.html.haml
%h1 #{@question.title}
=form_tag(question_responses_path(@question,@response), :method => "post") do
	-@question.answers.each do |answer|
		=label_tag :answer_id, answer.value
		=radio_button_tag :answer_id, answer.id
	=button_tag "Select", :class => "btn btn-success"

=generate_route_for_question

app/views/shared/_modal.html.erb
<div class="modal hide" id="modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><%= modal_title %></h3>
  </div>
  <div class="modal-body">
  </div>
  <%= render :partial => partial, :locals => partial_vars %>
<!--   <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div> -->
</div>